### ISSUE TITLE
Does this work asyncio.coroutine and yield from ?

### ISSUE THREAD

**Issue by stuaxo** [Skyscanner/pyfailsafe#25]
Since I use aiozmq I'm stuck on ```yield from``` and ```@asyncio.coroutine``` can pyfailsafe work be used with this style of async programming ?

**Comment by jakubka** [comment]
Hey @stuaxo, yes, it can be used with coroutines written using `yield from` and `@asyncio.coroutine`. You will however need to use Python 3.5 to run your app since pyfailsafe is written with async/await.

Let me know if you run into issues

**Comment by stuaxo** [comment]
Cheers :)
 S++ 

    On Friday, February 3, 2017 1:50 PM, Jakub Kadlubiec <notifications@github.com> wrote:
 

 Closed #25.—
